### PR TITLE
Merge branch 'master' into develop

### PR DESCRIPTION
**Pull request by LamVanHopee**
## Feature in this PR:
- [Issue #3](https://github.com/etvox-inc/sii_printer_flutter/issues/3) ([PR #10](https://github.com/etvox-inc/sii_printer_flutter/pull/10))

### CODE REVIEW

**Comment by ujway** [comment]
Thank you for giving PR. I will approve later after current app develop is released.

**Comment by LamVanHopee** [comment]
I'm so sorry for the trouble I've caused you.

**Review by ujway — APPROVED** [review]
LGTM!

**Comment by ujway** [comment]
Merge?

**Comment by LamVanHopee** [comment]
> Merge?

Ok, I merge it right now.

**Comment by ujway** [comment]
Thank you

**Pull request merged**
