### PR TITLE
Feature/issue 3

### PR DESCRIPTION
**Pull request by LamVanHopee**
Issue #3

### CODE REVIEW

**Comment by LamVanHopee** [comment]
Screen Shot 2022-03-24 at 6 04 25 PM
@ujway 
I have created 2 ways to get the image path. Please let me know which one works or doesn't work.
Thank you very much.

**Comment by ujway** [comment]
@LamVanHopee 
Sorry I didn't realize that. I tested the features but images got garbled.
Screen Shot 2022-04-20 at 14 49 23

**Comment by ujway** [comment]
@LamVanHopee Seems to get not found error.
Screen Shot 2022-04-20 at 16 19 19

**Comment by LamVanHopee** [comment]
> @LamVanHopee Seems to get not found error. Screen Shot 2022-04-20 at 16 19 19

@ujway  For both case?

**Comment by ujway** [comment]
Yes. Abobe is for logo 1 and here is logo 2
Screen Shot 2022-04-20 at 16 29 42

**Comment by LamVanHopee** [comment]
@ujway 
the case of logo2 seems more positive. `OVER_MAX_IMAGE` is Printer error. I will try to resize image.

**Comment by ujway** [comment]
@LamVanHopee Good, OK. If you need more my helps, please let me know.

**Comment by ujway** [comment]
@LamVanHopee Oh image was printed with logo 2
Screen Shot 2022-04-20 at 16 56 17

logo 1 has still an error below,
Screen Shot 2022-04-20 at 16 57 01

**Pull request closed without merging**
